### ISSUE TITLE
바닐라간에서 어떤 데이터를 사용한 건가요?

### ISSUE THREAD

**Issue by HYUNMIN-HWANG** [zashin-AI/youngri#1]
https://github.com/zashin-AI/youngri/blob/34c38c73a7705fe8af24fc72817e29ef71ec21ed/gan/make_gan_06_vanilla_03.py#L17-L23

간에서 사용한 데이터에 대한 궁금증 !
female이랑 male 음성 둘 다 들어간건가요?

**Comment by YoungriKIM** [comment]
19,200개의 데이터 중 female 9,600개만 사용했습니다.

해당 파일은  female(0) / male(1) 으로 구분할 모델에
사용 할 수 있는 새로운 데이터를 만들기 위해 gan을 시도해본 것입니다.
현재 잡음은 존재하지만 음정이 높은 음성이 만들어졌습니다!
